### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by bennycode** [welovecoding/welovecoding#17]
After the Passport & Sequelize merge (#16) I just tried to deploy a new version by changing some text payloads: https://github.com/welovecoding/welovecoding/commit/9c8a5d6bd6535574607ae376705be0414a356834

The Heroku deployment failed, resulting in the following deployment:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by bennycode** [comment]
Debugging result from `heroku logs --app=welovecoding --tail`:

> 2017-06-04T11:47:51.464819+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-04T11:47:51.244566+00:00 app[web.1]: /app/backend/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25
2017-06-04T11:47:51.244579+00:00 app[web.1]:       throw new Error('Please install sqlite3 package manually');
2017-06-04T11:47:51.244580+00:00 app[web.1]:       ^
2017-06-04T11:47:51.244581+00:00 app[web.1]:
2017-06-04T11:47:51.244582+00:00 app[web.1]: Error: Please install sqlite3 package manually
2017-06-04T11:47:51.244583+00:00 app[web.1]:     at new ConnectionManager (/app/backend/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
2017-06-04T11:47:51.244583+00:00 app[web.1]:     at new SqliteDialect (/app/backend/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
2017-06-04T11:47:51.244584+00:00 app[web.1]:     at Sequelize (/app/backend/node_modules/sequelize/lib/sequelize.js:233:18)
2017-06-04T11:47:51.244584+00:00 app[web.1]:     at new Sequelize (/app/backend/node_modules/sequelize-typescript/lib/models/v3/Sequelize.js:36:16)
2017-06-04T11:47:51.244585+00:00 app[web.1]:     at Object.defineProperty.value (/app/backend/dist/main.js:692:19)
2017-06-04T11:47:51.244586+00:00 app[web.1]:     at __webpack_require__ (/app/backend/dist/main.js:20:30)
2017-06-04T11:47:51.244587+00:00 app[web.1]:     at Object.defineProperty.value (/app/backend/dist/main.js:825:18)
2017-06-04T11:47:51.244587+00:00 app[web.1]:     at __webpack_require__ (/app/backend/dist/main.js:20:30)
2017-06-04T11:47:51.244588+00:00 app[web.1]:     at Object.<anonymous> (/app/backend/dist/main.js:879:18)
2017-06-04T11:47:51.244588+00:00 app[web.1]:     at __webpack_require__ (/app/backend/dist/main.js:20:30)
2017-06-04T11:47:51.244589+00:00 app[web.1]:     at /app/backend/dist/main.js:66:18
2017-06-04T11:47:51.244589+00:00 app[web.1]:     at Object.<anonymous> (/app/backend/dist/main.js:69:10)
2017-06-04T11:47:51.244590+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-06-04T11:47:51.244590+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-04T11:47:51.244591+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-04T11:47:51.244591+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)

**Comment by bennycode** [comment]
Resolved issue by removing the standalone `sequelize` statement: https://github.com/welovecoding/welovecoding/commit/8553074c1930f139d278a7228ce9bda25e0b3519#diff-ac9e8a694098db2ffc230455f59af8adL11
