### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bennycode** [welovecoding/welovecoding#63]
The webapp crashes when trying to login with Google. I run `database:reset` and `database:populate` beforehand but it didn't help. :(

> [0] [1] D:\dev\projects\welovecoding\welovecoding\backend\dist\webpack:\src\controllers\UserController.ts:8
[0] [1]         id: user.id,
[0] [1] ^
[0] [1] TypeError: Cannot read property 'id' of undefined
[0] [1]     at Object.generateToken (D:\dev\projects\welovecoding\welovecoding\backend\dist\webpack:\src\controllers\UserController.ts:8:1)
[0] [1]     at D:\dev\projects\welovecoding\welovecoding\backend\dist\webpack:\src\routes\UserRoutes.ts:69:1
[0] [1]     at Strategy.strategy.error (D:\dev\projects\welovecoding\welovecoding\backend\node_modules\passport\lib\middleware\authenticate.js:340:18)
[0] [1]     at D:\dev\projects\welovecoding\welovecoding\backend\node_modules\passport-oauth2\lib\strategy.js:166:34
[0] [1]     at D:\dev\projects\welovecoding\welovecoding\backend\node_modules\oauth\lib\oauth2.js:191:18
[0] [1]     at passBackControl (D:\dev\projects\welovecoding\welovecoding\backend\node_modules\oauth\lib\oauth2.js:132:9)
[0] [1]     at IncomingMessage.<anonymous> (D:\dev\projects\welovecoding\welovecoding\backend\node_modules\oauth\lib\oauth2.js:157:7)
[0] [1]     at emitNone (events.js:110:20)
[0] [1]     at IncomingMessage.emit (events.js:207:7)
[0] [1]     at endReadableNT (_stream_readable.js:1047:12)
[0] [1]     at _combinedTickCallback (internal/process/next_tick.js:102:11)
[0] [1]     at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by TN1ck** [comment]
Try this:

1. clone the repo again
2. put valid env-vars in backend/.env
3. execute yarn in the root directory
4. execute `yarn start` in `backend`
5. execute `yarn database:reset` in `backend`
6. execute `yarn database:populate` in `backend`
7. execute `yarn start` in `frontend`
8. make sure postgres is running and correctly set up

Does it still throw this error, because I just did that and it worked.
